"""Add authentication models and user fields

Revision ID: 15db5c883765
Revises: 6b5bd0651054
Create Date: 2025-11-14 07:42:49.823638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15db5c883765'
down_revision: Union[str, None] = '6b5bd0651054'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_verifications',
    sa.Column('verification_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('expires_at', sa.Date(), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.Column('verified_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('verification_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_email_verifications_token'), 'email_verifications', ['token'], unique=True)
    op.create_index(op.f('ix_email_verifications_verification_id'), 'email_verifications', ['verification_id'], unique=False)
    op.create_table('password_resets',
    sa.Column('reset_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.Column('expires_at', sa.Date(), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.Column('used_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('reset_id')
    )
    op.create_index(op.f('ix_password_resets_reset_id'), 'password_resets', ['reset_id'], unique=False)
    op.create_index(op.f('ix_password_resets_token'), 'password_resets', ['token'], unique=True)
    op.create_table('two_factor_auths',
    sa.Column('two_factor_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('secret_key', sa.String(length=255), nullable=True),
    sa.Column('backup_codes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.Column('last_used_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('two_factor_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_two_factor_auths_two_factor_id'), 'two_factor_auths', ['two_factor_id'], unique=False)
    op.create_table('two_factor_codes',
    sa.Column('code_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('expires_at', sa.Date(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('code_id')
    )
    op.create_index(op.f('ix_two_factor_codes_code_id'), 'two_factor_codes', ['code_id'], unique=False)
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), nullable=True, server_default='false'))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True, server_default='true'))
    
    # Update existing users to have default values
    op.execute("UPDATE users SET email_verified = false WHERE email_verified IS NULL")
    op.execute("UPDATE users SET is_active = true WHERE is_active IS NULL")
    
    # Make columns NOT NULL after setting defaults
    op.alter_column('users', 'email_verified', nullable=False, server_default='false')
    op.alter_column('users', 'is_active', nullable=False, server_default='true')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'email_verified')
    op.drop_index(op.f('ix_two_factor_codes_code_id'), table_name='two_factor_codes')
    op.drop_table('two_factor_codes')
    op.drop_index(op.f('ix_two_factor_auths_two_factor_id'), table_name='two_factor_auths')
    op.drop_table('two_factor_auths')
    op.drop_index(op.f('ix_password_resets_token'), table_name='password_resets')
    op.drop_index(op.f('ix_password_resets_reset_id'), table_name='password_resets')
    op.drop_table('password_resets')
    op.drop_index(op.f('ix_email_verifications_verification_id'), table_name='email_verifications')
    op.drop_index(op.f('ix_email_verifications_token'), table_name='email_verifications')
    op.drop_table('email_verifications')
    # ### end Alembic commands ###

