"""add_user_upgrade_requests_table

Revision ID: b4699509a8d0
Revises: 15db5c883765
Create Date: 2025-11-14 14:11:30.845337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4699509a8d0'
down_revision: Union[str, None] = '15db5c883765'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_upgrade_requests',
    sa.Column('upgrade_request_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('current_user_type', sa.String(length=50), nullable=False),
    sa.Column('requested_user_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='upgraderequeststatus'), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('business_name', sa.String(length=200), nullable=True),
    sa.Column('business_description', sa.String(length=1000), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.Date(), nullable=True),
    sa.Column('rejection_reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('upgrade_request_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_user_upgrade_requests_upgrade_request_id'), 'user_upgrade_requests', ['upgrade_request_id'], unique=False)
    op.alter_column('users', 'email_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'email_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_user_upgrade_requests_upgrade_request_id'), table_name='user_upgrade_requests')
    op.drop_table('user_upgrade_requests')
    # ### end Alembic commands ###

