"""initial migration

Revision ID: c3cd43a24d28
Revises: 
Create Date: 2025-11-15 09:14:11.477188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3cd43a24d28'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('category_id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_categories_category_id'), 'categories', ['category_id'], unique=False)
    op.create_table('distribution_levels',
    sa.Column('level_id', sa.Integer(), nullable=False),
    sa.Column('level_number', sa.Integer(), nullable=False),
    sa.Column('distribution_percentage', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('level_id'),
    sa.UniqueConstraint('level_number')
    )
    op.create_index(op.f('ix_distribution_levels_level_id'), 'distribution_levels', ['level_id'], unique=False)
    op.create_table('event_funds',
    sa.Column('fund_id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('fund_id')
    )
    op.create_index(op.f('ix_event_funds_fund_id'), 'event_funds', ['fund_id'], unique=False)
    op.create_table('hashtags',
    sa.Column('hashtag_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('trending', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('hashtag_id')
    )
    op.create_index(op.f('ix_hashtags_hashtag_id'), 'hashtags', ['hashtag_id'], unique=False)
    op.create_index(op.f('ix_hashtags_name'), 'hashtags', ['name'], unique=True)
    op.create_table('locations',
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('location_id')
    )
    op.create_index(op.f('ix_locations_location_id'), 'locations', ['location_id'], unique=False)
    op.create_table('monetizable_actions',
    sa.Column('action_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.Enum('SHARE', 'RESPOND', 'VIEW', 'SPONSOR', name='actiontype'), nullable=False),
    sa.Column('base_value', sa.Float(), nullable=False),
    sa.Column('multiplier', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('action_id')
    )
    op.create_index(op.f('ix_monetizable_actions_action_id'), 'monetizable_actions', ['action_id'], unique=False)
    op.create_table('multiplier_plans',
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('multiplier_factor', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('plan_id')
    )
    op.create_index(op.f('ix_multiplier_plans_plan_id'), 'multiplier_plans', ['plan_id'], unique=False)
    op.create_table('tax_data',
    sa.Column('tax_data_id', sa.Integer(), nullable=False),
    sa.Column('document', sa.String(length=50), nullable=False),
    sa.Column('bank_account', sa.String(length=100), nullable=True),
    sa.Column('tax_regime', sa.String(length=100), nullable=True),
    sa.Column('withholdings', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('tax_data_id')
    )
    op.create_index(op.f('ix_tax_data_tax_data_id'), 'tax_data', ['tax_data_id'], unique=False)
    op.create_table('transcoding_profiles',
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('video_codec', sa.String(length=50), nullable=False),
    sa.Column('video_bitrate', sa.Integer(), nullable=True),
    sa.Column('video_bitrate_mode', sa.String(length=20), nullable=True),
    sa.Column('resolution_width', sa.Integer(), nullable=True),
    sa.Column('resolution_height', sa.Integer(), nullable=True),
    sa.Column('fps', sa.Float(), nullable=True),
    sa.Column('keyframe_interval', sa.Integer(), nullable=True),
    sa.Column('audio_codec', sa.String(length=50), nullable=True),
    sa.Column('audio_bitrate', sa.Integer(), nullable=True),
    sa.Column('audio_sample_rate', sa.Integer(), nullable=True),
    sa.Column('audio_channels', sa.Integer(), nullable=True),
    sa.Column('container_format', sa.String(length=20), nullable=False),
    sa.Column('quality_preset', sa.String(length=50), nullable=True),
    sa.Column('crf', sa.Integer(), nullable=True),
    sa.Column('generate_thumbnail', sa.Boolean(), nullable=True),
    sa.Column('thumbnail_count', sa.Integer(), nullable=True),
    sa.Column('thumbnail_interval', sa.Integer(), nullable=True),
    sa.Column('enable_hls', sa.Boolean(), nullable=True),
    sa.Column('enable_dash', sa.Boolean(), nullable=True),
    sa.Column('segment_duration', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('profile_id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_transcoding_profiles_profile_id'), 'transcoding_profiles', ['profile_id'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_type', sa.Enum('USER', 'ADMIN', 'SUPER_ADMIN', name='usertype'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('profile_picture', sa.String(length=500), nullable=True),
    sa.Column('cover_picture', sa.String(length=500), nullable=True),
    sa.Column('biography', sa.String(length=500), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('tax_data_id', sa.Integer(), nullable=True),
    sa.Column('multiplier_plan_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('following_count', sa.Integer(), nullable=True),
    sa.Column('followers_count', sa.Integer(), nullable=True),
    sa.Column('registration_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.location_id'], ),
    sa.ForeignKeyConstraint(['multiplier_plan_id'], ['multiplier_plans.plan_id'], ),
    sa.ForeignKeyConstraint(['tax_data_id'], ['tax_data.tax_data_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('advertising_campaigns',
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=False),
    sa.Column('budget', sa.Float(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('campaign_id')
    )
    op.create_index(op.f('ix_advertising_campaigns_campaign_id'), 'advertising_campaigns', ['campaign_id'], unique=False)
    op.create_table('contents',
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.Enum('VIDEO', 'IMAGE', 'TEXT', 'AUDIO', name='contenttype'), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('format', sa.String(length=50), nullable=True),
    sa.Column('resolution', sa.String(length=50), nullable=True),
    sa.Column('assigned_budget', sa.Float(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('visibility', sa.Enum('PUBLIC', 'PRIVATE', name='visibility'), nullable=True),
    sa.Column('allow_comments', sa.Boolean(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.Column('published_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.location_id'], ),
    sa.ForeignKeyConstraint(['merchant_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('content_id')
    )
    op.create_index(op.f('ix_contents_content_id'), 'contents', ['content_id'], unique=False)
    op.create_table('email_verifications',
    sa.Column('verification_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('expires_at', sa.Date(), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.Column('verified_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('verification_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_email_verifications_token'), 'email_verifications', ['token'], unique=True)
    op.create_index(op.f('ix_email_verifications_verification_id'), 'email_verifications', ['verification_id'], unique=False)
    op.create_table('follows',
    sa.Column('follow_id', sa.Integer(), nullable=False),
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('followed_id', sa.Integer(), nullable=False),
    sa.Column('follow_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('follow_id'),
    sa.UniqueConstraint('follower_id', 'followed_id', name='uq_follow')
    )
    op.create_index(op.f('ix_follows_follow_id'), 'follows', ['follow_id'], unique=False)
    op.create_table('notifications',
    sa.Column('notification_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('notification_type', sa.Enum('LIKE', 'COMMENT', 'FOLLOW', 'MENTION', 'TRANSACTION', 'VOUCHER', 'OTHER', name='notificationtype'), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('notification_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_index(op.f('ix_notifications_notification_id'), 'notifications', ['notification_id'], unique=False)
    op.create_table('password_resets',
    sa.Column('reset_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.Column('expires_at', sa.Date(), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.Column('used_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('reset_id')
    )
    op.create_index(op.f('ix_password_resets_reset_id'), 'password_resets', ['reset_id'], unique=False)
    op.create_index(op.f('ix_password_resets_token'), 'password_resets', ['token'], unique=True)
    op.create_table('transactions',
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.Enum('VOUCHER_PURCHASE', 'WITHDRAWAL', 'ACTION_PAYMENT', name='transactiontype'), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'REJECTED', 'CANCELLED', name='transactionstatus'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_index(op.f('ix_transactions_transaction_id'), 'transactions', ['transaction_id'], unique=False)
    op.create_table('two_factor_auths',
    sa.Column('two_factor_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('secret_key', sa.String(length=255), nullable=True),
    sa.Column('backup_codes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.Column('last_used_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('two_factor_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_two_factor_auths_two_factor_id'), 'two_factor_auths', ['two_factor_id'], unique=False)
    op.create_table('two_factor_codes',
    sa.Column('code_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('expires_at', sa.Date(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('code_id')
    )
    op.create_index(op.f('ix_two_factor_codes_code_id'), 'two_factor_codes', ['code_id'], unique=False)
    op.create_table('user_categories',
    sa.Column('user_category_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.category_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_category_id'),
    sa.UniqueConstraint('user_id', 'category_id', name='uq_user_category'),
    sqlite_autoincrement=True
    )
    op.create_index(op.f('ix_user_categories_user_category_id'), 'user_categories', ['user_category_id'], unique=False)
    op.create_table('user_plans',
    sa.Column('user_plan_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=False),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['multiplier_plans.plan_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_plan_id')
    )
    op.create_index(op.f('ix_user_plans_user_plan_id'), 'user_plans', ['user_plan_id'], unique=False)
    op.create_table('user_preferences',
    sa.Column('preference_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('algorithm_preference', sa.String(length=50), nullable=True),
    sa.Column('push_notifications', sa.Boolean(), nullable=True),
    sa.Column('email_notifications', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('preference_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_user_preferences_preference_id'), 'user_preferences', ['preference_id'], unique=False)
    op.create_table('comments',
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('parent_comment_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.String(length=1000), nullable=False),
    sa.Column('comment_date', sa.Date(), nullable=True),
    sa.Column('edited', sa.Boolean(), nullable=True),
    sa.Column('edit_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['contents.content_id'], ),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['comments.comment_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('comment_id')
    )
    op.create_index(op.f('ix_comments_comment_id'), 'comments', ['comment_id'], unique=False)
    op.create_table('content_categories',
    sa.Column('content_category_id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.category_id'], ),
    sa.ForeignKeyConstraint(['content_id'], ['contents.content_id'], ),
    sa.PrimaryKeyConstraint('content_category_id'),
    sa.UniqueConstraint('content_id', 'category_id', name='uq_content_category'),
    sqlite_autoincrement=True
    )
    op.create_index(op.f('ix_content_categories_content_category_id'), 'content_categories', ['content_category_id'], unique=False)
    op.create_table('content_hashtags',
    sa.Column('content_hashtag_id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('hashtag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['contents.content_id'], ),
    sa.ForeignKeyConstraint(['hashtag_id'], ['hashtags.hashtag_id'], ),
    sa.PrimaryKeyConstraint('content_hashtag_id'),
    sqlite_autoincrement=True
    )
    op.create_index(op.f('ix_content_hashtags_content_hashtag_id'), 'content_hashtags', ['content_hashtag_id'], unique=False)
    op.create_table('content_metrics',
    sa.Column('metric_id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('likes_count', sa.Integer(), nullable=True),
    sa.Column('comments_count', sa.Integer(), nullable=True),
    sa.Column('shares_count', sa.Integer(), nullable=True),
    sa.Column('average_view_duration', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['contents.content_id'], ),
    sa.PrimaryKeyConstraint('metric_id'),
    sa.UniqueConstraint('content_id')
    )
    op.create_index(op.f('ix_content_metrics_metric_id'), 'content_metrics', ['metric_id'], unique=False)
    op.create_table('feed_items',
    sa.Column('feed_item_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.Date(), nullable=True),
    sa.Column('viewed', sa.Boolean(), nullable=True),
    sa.Column('viewed_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['contents.content_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('feed_item_id')
    )
    op.create_index(op.f('ix_feed_items_feed_item_id'), 'feed_items', ['feed_item_id'], unique=False)
    op.create_table('interactions',
    sa.Column('interaction_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('action_id', sa.Integer(), nullable=False),
    sa.Column('amount_paid', sa.Float(), nullable=True),
    sa.Column('interaction_date', sa.Date(), nullable=True),
    sa.Column('validated', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['action_id'], ['monetizable_actions.action_id'], ),
    sa.ForeignKeyConstraint(['content_id'], ['contents.content_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('interaction_id')
    )
    op.create_index(op.f('ix_interactions_interaction_id'), 'interactions', ['interaction_id'], unique=False)
    op.create_table('likes',
    sa.Column('like_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('like_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['contents.content_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('like_id'),
    sa.UniqueConstraint('user_id', 'content_id', name='uq_like')
    )
    op.create_index(op.f('ix_likes_like_id'), 'likes', ['like_id'], unique=False)
    op.create_table('multimedia_files',
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('file_type', sa.Enum('VIDEO', 'AUDIO', 'IMAGE', 'THUMBNAIL', 'OTHER', name='filetype'), nullable=False),
    sa.Column('bucket_name', sa.String(length=100), nullable=False),
    sa.Column('s3_key', sa.String(length=500), nullable=False),
    sa.Column('s3_url', sa.String(length=1000), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('format', sa.String(length=50), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('resolution', sa.String(length=50), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('bitrate', sa.Integer(), nullable=True),
    sa.Column('fps', sa.Float(), nullable=True),
    sa.Column('sample_rate', sa.Integer(), nullable=True),
    sa.Column('channels', sa.Integer(), nullable=True),
    sa.Column('processing_status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'ERROR', name='processingstatus'), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('cdn_url', sa.String(length=1000), nullable=True),
    sa.Column('preview_url', sa.String(length=1000), nullable=True),
    sa.Column('uploaded_at', sa.Date(), nullable=True),
    sa.Column('processed_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['contents.content_id'], ),
    sa.PrimaryKeyConstraint('file_id')
    )
    op.create_index(op.f('ix_multimedia_files_file_id'), 'multimedia_files', ['file_id'], unique=False)
    op.create_index(op.f('ix_multimedia_files_s3_key'), 'multimedia_files', ['s3_key'], unique=True)
    op.create_table('vouchers',
    sa.Column('voucher_id', sa.Integer(), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('qr_code', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'REDEEMED', 'EXPIRED', name='voucherstatus'), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.Column('expires_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.transaction_id'], ),
    sa.PrimaryKeyConstraint('voucher_id'),
    sa.UniqueConstraint('transaction_id')
    )
    op.create_index(op.f('ix_vouchers_qr_code'), 'vouchers', ['qr_code'], unique=True)
    op.create_index(op.f('ix_vouchers_voucher_id'), 'vouchers', ['voucher_id'], unique=False)
    op.create_table('file_versions',
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('original_file_id', sa.Integer(), nullable=False),
    sa.Column('quality', sa.String(length=50), nullable=False),
    sa.Column('resolution', sa.String(length=50), nullable=True),
    sa.Column('s3_key', sa.String(length=500), nullable=False),
    sa.Column('s3_url', sa.String(length=1000), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('format', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['original_file_id'], ['multimedia_files.file_id'], ),
    sa.PrimaryKeyConstraint('version_id')
    )
    op.create_index(op.f('ix_file_versions_s3_key'), 'file_versions', ['s3_key'], unique=True)
    op.create_index(op.f('ix_file_versions_version_id'), 'file_versions', ['version_id'], unique=False)
    op.create_table('payment_distributions',
    sa.Column('distribution_id', sa.Integer(), nullable=False),
    sa.Column('interaction_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('distribution_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['interaction_id'], ['interactions.interaction_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('distribution_id')
    )
    op.create_index(op.f('ix_payment_distributions_distribution_id'), 'payment_distributions', ['distribution_id'], unique=False)
    op.create_table('sales_commissions',
    sa.Column('commission_id', sa.Integer(), nullable=False),
    sa.Column('voucher_id', sa.Integer(), nullable=False),
    sa.Column('commission_amount', sa.Float(), nullable=False),
    sa.Column('distributed', sa.Boolean(), nullable=True),
    sa.Column('calculated_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['voucher_id'], ['vouchers.voucher_id'], ),
    sa.PrimaryKeyConstraint('commission_id')
    )
    op.create_index(op.f('ix_sales_commissions_commission_id'), 'sales_commissions', ['commission_id'], unique=False)
    op.create_table('transcoding_jobs',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('source_file_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'QUEUED', 'PROCESSING', 'COMPLETED', 'FAILED', 'CANCELLED', name='transcodingstatus'), nullable=True),
    sa.Column('priority', sa.Enum('LOW', 'NORMAL', 'HIGH', 'URGENT', name='transcodingpriority'), nullable=True),
    sa.Column('progress_percentage', sa.Float(), nullable=True),
    sa.Column('started_at', sa.Date(), nullable=True),
    sa.Column('completed_at', sa.Date(), nullable=True),
    sa.Column('estimated_completion', sa.Date(), nullable=True),
    sa.Column('processing_time_seconds', sa.Float(), nullable=True),
    sa.Column('output_file_id', sa.Integer(), nullable=True),
    sa.Column('output_s3_key', sa.String(length=500), nullable=True),
    sa.Column('output_s3_url', sa.String(length=1000), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_code', sa.String(length=50), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('max_retries', sa.Integer(), nullable=True),
    sa.Column('worker_id', sa.String(length=100), nullable=True),
    sa.Column('processor_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['output_file_id'], ['multimedia_files.file_id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['transcoding_profiles.profile_id'], ),
    sa.ForeignKeyConstraint(['source_file_id'], ['multimedia_files.file_id'], ),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_index(op.f('ix_transcoding_jobs_job_id'), 'transcoding_jobs', ['job_id'], unique=False)
    op.create_table('transcoding_logs',
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('log_level', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('log_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['transcoding_jobs.job_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_transcoding_logs_log_id'), 'transcoding_logs', ['log_id'], unique=False)
    op.create_table('transcoding_queue',
    sa.Column('queue_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('queued_at', sa.Date(), nullable=True),
    sa.Column('started_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['transcoding_jobs.job_id'], ),
    sa.PrimaryKeyConstraint('queue_id'),
    sa.UniqueConstraint('job_id')
    )
    op.create_index(op.f('ix_transcoding_queue_queue_id'), 'transcoding_queue', ['queue_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transcoding_queue_queue_id'), table_name='transcoding_queue')
    op.drop_table('transcoding_queue')
    op.drop_index(op.f('ix_transcoding_logs_log_id'), table_name='transcoding_logs')
    op.drop_table('transcoding_logs')
    op.drop_index(op.f('ix_transcoding_jobs_job_id'), table_name='transcoding_jobs')
    op.drop_table('transcoding_jobs')
    op.drop_index(op.f('ix_sales_commissions_commission_id'), table_name='sales_commissions')
    op.drop_table('sales_commissions')
    op.drop_index(op.f('ix_payment_distributions_distribution_id'), table_name='payment_distributions')
    op.drop_table('payment_distributions')
    op.drop_index(op.f('ix_file_versions_version_id'), table_name='file_versions')
    op.drop_index(op.f('ix_file_versions_s3_key'), table_name='file_versions')
    op.drop_table('file_versions')
    op.drop_index(op.f('ix_vouchers_voucher_id'), table_name='vouchers')
    op.drop_index(op.f('ix_vouchers_qr_code'), table_name='vouchers')
    op.drop_table('vouchers')
    op.drop_index(op.f('ix_multimedia_files_s3_key'), table_name='multimedia_files')
    op.drop_index(op.f('ix_multimedia_files_file_id'), table_name='multimedia_files')
    op.drop_table('multimedia_files')
    op.drop_index(op.f('ix_likes_like_id'), table_name='likes')
    op.drop_table('likes')
    op.drop_index(op.f('ix_interactions_interaction_id'), table_name='interactions')
    op.drop_table('interactions')
    op.drop_index(op.f('ix_feed_items_feed_item_id'), table_name='feed_items')
    op.drop_table('feed_items')
    op.drop_index(op.f('ix_content_metrics_metric_id'), table_name='content_metrics')
    op.drop_table('content_metrics')
    op.drop_index(op.f('ix_content_hashtags_content_hashtag_id'), table_name='content_hashtags')
    op.drop_table('content_hashtags')
    op.drop_index(op.f('ix_content_categories_content_category_id'), table_name='content_categories')
    op.drop_table('content_categories')
    op.drop_index(op.f('ix_comments_comment_id'), table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_user_preferences_preference_id'), table_name='user_preferences')
    op.drop_table('user_preferences')
    op.drop_index(op.f('ix_user_plans_user_plan_id'), table_name='user_plans')
    op.drop_table('user_plans')
    op.drop_index(op.f('ix_user_categories_user_category_id'), table_name='user_categories')
    op.drop_table('user_categories')
    op.drop_index(op.f('ix_two_factor_codes_code_id'), table_name='two_factor_codes')
    op.drop_table('two_factor_codes')
    op.drop_index(op.f('ix_two_factor_auths_two_factor_id'), table_name='two_factor_auths')
    op.drop_table('two_factor_auths')
    op.drop_index(op.f('ix_transactions_transaction_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_password_resets_token'), table_name='password_resets')
    op.drop_index(op.f('ix_password_resets_reset_id'), table_name='password_resets')
    op.drop_table('password_resets')
    op.drop_index(op.f('ix_notifications_notification_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_follows_follow_id'), table_name='follows')
    op.drop_table('follows')
    op.drop_index(op.f('ix_email_verifications_verification_id'), table_name='email_verifications')
    op.drop_index(op.f('ix_email_verifications_token'), table_name='email_verifications')
    op.drop_table('email_verifications')
    op.drop_index(op.f('ix_contents_content_id'), table_name='contents')
    op.drop_table('contents')
    op.drop_index(op.f('ix_advertising_campaigns_campaign_id'), table_name='advertising_campaigns')
    op.drop_table('advertising_campaigns')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_transcoding_profiles_profile_id'), table_name='transcoding_profiles')
    op.drop_table('transcoding_profiles')
    op.drop_index(op.f('ix_tax_data_tax_data_id'), table_name='tax_data')
    op.drop_table('tax_data')
    op.drop_index(op.f('ix_multiplier_plans_plan_id'), table_name='multiplier_plans')
    op.drop_table('multiplier_plans')
    op.drop_index(op.f('ix_monetizable_actions_action_id'), table_name='monetizable_actions')
    op.drop_table('monetizable_actions')
    op.drop_index(op.f('ix_locations_location_id'), table_name='locations')
    op.drop_table('locations')
    op.drop_index(op.f('ix_hashtags_name'), table_name='hashtags')
    op.drop_index(op.f('ix_hashtags_hashtag_id'), table_name='hashtags')
    op.drop_table('hashtags')
    op.drop_index(op.f('ix_event_funds_fund_id'), table_name='event_funds')
    op.drop_table('event_funds')
    op.drop_index(op.f('ix_distribution_levels_level_id'), table_name='distribution_levels')
    op.drop_table('distribution_levels')
    op.drop_index(op.f('ix_categories_category_id'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###

